### ISSUE TITLE
ngsReveal shows only the viewport "items"

### ISSUE THREAD

**Issue by Sonntagskind** [tinesoft/ng2-scrollreveal#2]
Hello! 
The issue is that only the "items" which are in the viewport on load are shown, the others are hidden even on scroll.

 If the viewport is big enough by default to contain two divs, the divs are shown onload, if the viewport is smaller and can place only one div, this div is shown only, no other divs appear on scroll.

**OS:** ElCapitan 10.11.3
**Browser:** Chrome 53.0.2785.143 (64-bit)
**scrollreveal:** ^3.3.2
**ng2-scrollreveal:** ^1.0.0

Both the Chrome console and Terminal show no errors, warnings, etc.

My code for scroll reveal section:

`   
         
       <div class="itemset about" ngsRevealSet [ngsSelector]="'.item'">

	   <div class="item one"> Block One </div>

      <div class="item two"> Block Two </div>

	   <div class="item three"> Block Three </div>

	   <div class="item four"> Block Four </div>

        </div>

`

My CSS for that section:
`
/*****About*****/
.about {
  overflow: auto;
  height: 100%;
  width: 100%;
  font-size: 2rem;
  margin-top: 70px;
  text-align: center;
}

.item {
	height: 400px;
}

.one {
	background: red;
}

.two {
	background: yellow;
}

.three {
	background: grey;
}

.four {
	background: cyan;
}
`

I also inspected the hidden blocks in the Chrome console, and they have

`opacity:0;
visibility:visible;
`

and animation is at the starting point (when I manually change the visibility property, the divs shown as they are stuck in the very beginning of animation).

I also use Bootstrap grid (only!), but as I can see there are no intersected styles. So, everything should work correctly, but it doesn't.

**Comment by tinesoft** [comment]
Hi @Sonntagskind ,

Can you provide a simple plunker with the issue? 

I have created [one](http://plnkr.co/Wo14VA) with the info you provided, but i can't reproduce the problem (all blocks, even those not visible at beginning, still appear on scroll down)

Please, also note that your are using the simplest form of the `ngsRevealSet` directive (i.e without any configuration object passed along),  so by default, items are only animated once (no reset when you scroll up <-> scroll down). You need to use  at least `[ngsRevealSet]="{reset: true}"` for that.

**Comment by Sonntagskind** [comment]
@tinesoft, I was trying to make a plunker, but had no success on recreating my situation - too many files and dependencies.

I found the issue
https://github.com/jlmakes/scrollreveal/issues/315

And I think that I have smth similar to it. But I have no custom setup for Scrollreveal, just the default one.

What I tried:
1) Changed the line in my **scrollreveal.js** file
`container: 'window.document.documentElement',`
to
`container: '.about',` //my div with Scrollreveal elements

2) According to the issue replies
https://github.com/jlmakes/scrollreveal/issues/105
I configured the viewport to be ('.about') div

But none of them helped.

To simplify the explanation, let's say my divs stucture is:
Wrapper div -> About div -> Scrollreveal divs

The Wrapper div styles:
`.wrapper {
  height: 100%;
  width: 100%;
  overflow: hidden;
  padding: 0 10px;
}`

The About div styles:
`.about {
  overflow-y: scroll;
  height: 100%;
  width: 100%;
  font-size: 2rem;
  margin-top: 70px;
  text-align: center;
}`

The Scrollreveal divs styles:
`.item {
	height: 200px;
}//and some bgr colors which don't matter I think`

What I know is that Scrollreveal doesn't work for the divs which are "outside" viewport on load, but in the console I can manually make them visible changing the styles. And I have no errors both in the console and Terminal.

**Comment by tinesoft** [comment]
Hi @Sonntagskind ,

Sorry for the delay, 'been kind of busy these past days.

The good news is that i could reproduced and fixed your issue (see my  [updated plunker ](http://plnkr.co/Wo14VA))

The key was indeed setting the `container` option. but instead of setting it to be  `.wrapper`  or `.about`, i set it to `.itemset` , the direct parent  of the items being revealed as part of the set.

This used to be the default behavior of `ngsRevealSet ` when i initially started the development. But i changed it back to stick closely to original behavior of Scrollreveal JS, which is to use default container `window.document.documentElement`, unless explicitly changed via custom options.

Let me know if it works for you.

**Comment by Sonntagskind** [comment]
Hello @tinesoft,

Thanks for your concern! But your [updated plunker example](http://plnkr.co/Wo14VA) isn't working to me - the same only 1st red block is visible (both for upload and scroll).

I changed the container property to '.itemset' in the node_modules > scrollreveal > src > scrollreveal.js file. But it didn't help as well. Was I supposed to change that file?

**Comment by tinesoft** [comment]
Hi,

You are not supposed to change any of scrollreveal or ng2-scrollreveal js files, 
but instead override the default container,  by providing custom configuration object to the directive
as such:
```
    <div class="itemset about" [ngsRevealSet]="{reset: true, container: '.itemset'}" [ngsSelector]="'.item'">
       <div class="item one"> Block One </div>
       <div class="item two"> Block Two </div>
       <div class="item three"> Block Three </div>
       <div class="item four"> Block Four </div>
    </div>
```
(**note**: you only provide parameters you want to override, here only the _`reset`_ and _`container`_ parameters will be overridden)

The plunker _does_ work when you click "Launch in Editor". Try it you'll see.

Anyway, the problem is not related to ng2-scrollreveal, and  Scrollreveal JS is already doing everything so that, animations are launched on init or when you scroll /up/dow a custom container. You just need to find the appropriate value for your `container`.

Without your exact layout and css, it will be difficult to further assist you.

**Comment by Sonntagskind** [comment]
Hi, @tinesoft!

Got it! Now it's working perfectly, MUCH thanx for your help!

**Comment by tinesoft** [comment]
Neat-o!

**Comment by eddsnchz** [comment]
I have the same problem, but when adding what you comment @tinesoft it already shows my divs but does not make any animation, I am programming from angular. Could you help me?
