### ISSUE TITLE
Cannot find type definition file for 'scrollreveal'

### ISSUE THREAD

**Issue by snowywolfie** [tinesoft/ng2-scrollreveal#3]
Hi, I encountered these errors below in terminal during ng serve but somehow it works in browser.  Any idea how to solve this?

node_modules/ng2-scrollreveal/ngs-reveal.service.d.ts:1:1 
Cannot find type definition file for 'scrollreveal'

ng2-scrollreveal/ngs-reveal.service.d.ts:17:63
Cannot find namespace 'scrollReveal'.

ng2-scrollreveal/ngs-reveal.service.d.ts:25:109 
Cannot find namespace 'scrollReveal'.

**Comment by tinesoft** [comment]
Hi @snowywolfie ,

Which version of the Angular CLI are you using? (run `ng version` and post output).
Did you follow steps mentioned in the [guide](https://github.com/tinesoft/ng2-scrollreveal#angular-cli) on how to use with CLI?

Also, can you post your `tsconfig.json` file?

**Comment by snowywolfie** [comment]
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

Yes, I included scrollreveal.js in scripts.

tsconfig.json
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

**Comment by tinesoft** [comment]
Ok, i'll have a look tonight, don't have access to my environment right now

**Comment by tinesoft** [comment]
Hi @snowywolfie ,

Regarding the errors you were having  while running `ng serve`,
the good news is that i was able to reproduce the issue locally.

This is due to the TypeScript Compiler (TSC) complaining about **missing types definition** for [Scrollreveal JS](https://scrollrevealjs.org). As this library is being used underneath by my `ngs-reveal.service.ts`, the compiler  has added a reference to it in generated definition file `ngs-reveal.service.d.ts`(1st line). This is the normal behavior of TSC.

You can get rid off the errors, by installing typings for scrollreval JS as well, via:

`npm install  @types/scrollreveal --save-dev`

I am thinking about a more elegant solution, but until then, that should make the CLI happy again :)

**Comment by snowywolfie** [comment]
Cool, It works like charm! I use the second method btw.
Thank you for prompt reply and efforts ! 👍

**Comment by tinesoft** [comment]
Neat-o!

Even better, i've tested with current version of Angular CLI (**beta-22-1**), and there is **no need to  install the `scrollreveal `typings anymore**, it just works out of the box!
There must have been some changes in the `ng build/serve` and/or angular customized version of tsc that made this possible.

I will update the docs.
